name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - '.gitignore'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up QEMU (for multi-platform support if needed)
        uses: docker/setup-qemu-action@49b3bc8e674a623743e4983a54d24606f799d14b # v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b7d897b47b4d391f1a5666735e054238e5 # v3

      - name: Log in to Docker Hub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e802778644893796791e2b453e9a03b3d162a # v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/server-dashboard:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/server-dashboard:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
